### ISSUE TITLE
zm_robot teleop

### ISSUE THREAD

**Issue by ceranfurkan11** [qaz9517532846/zm_robot#2]
When I run teleope key script, it works but robot does not move. please help me. I use ros noetic and ubuntu 20.04

**Comment by qaz9517532846** [comment]
you can use this command to check cmd_vel topic connected to gazebo plugin from teleop node:
 rosrun rqt_graph rqt_graph

**Comment by ceranfurkan11** [comment]
I see tb3 teleop. but I dont know how ıt works for zm_robot. I tried original tb3 teleop script and ıt does not works for zm_robot.

**Comment by qaz9517532846** [comment]
You can try to command zm_robot_teleope_key package control zm_robot, Please check topic name is /cmd_vel.

rosrun zm_robot_teleope_key zm_robot_teleope_key.py
.
![rosgraph](https://github.com/qaz9517532846/zm_robot/assets/48936051/52b5ca70-b538-4fcd-bc96-e1dd738af74c)

**Comment by ceranfurkan11** [comment]
topic name is correct. the robot still does not move.
![Screenshot from 2023-06-28 21-33-34](https://github.com/qaz9517532846/zm_robot/assets/117391958/6232712f-a25a-4f66-b00c-869f0dd4c93e)
