### ISSUE TITLE
Unable to do catkin_make command

### ISSUE THREAD

**Issue by RodrigoDomingues18** [qaz9517532846/zm_robot#5]
Hi. I created a workspace where inside the src directory cloned all your packages as described in the main page. But it shows the following error:
-- Could NOT find people_msgs (missing: people_msgs_DIR)
-- Could not find the required component 'people_msgs'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/noetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "people_msgs" with
  any of the following names:

    people_msgsConfig.cmake
    people_msgs-config.cmake

  Add the installation prefix of "people_msgs" to CMAKE_PREFIX_PATH or set
  "people_msgs_DIR" to a directory containing one of the above files.  If
  "people_msgs" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  navigation_layers/social_navigation_layers/CMakeLists.txt:5 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/sa/zm_robot_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/sa/zm_robot_ws/build/CMakeFiles/CMakeError.log".
make: *** [Makefile:2294: cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed

**Comment by qaz9517532846** [comment]
Sorry for the late reply. This issue need install ros package people_msgs.

sudo apt-get install ros-noetic-people-msgs.
